name: Dependabot MD Updates
on: pull_request
jobs:
  markdown-updates:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' 
      && ${{ ! contains(github.event.pull_request.title, 'dev.kikugie.stonecutter') }} 
      && ${{ ! contains(github.event.pull_request.title, 'com.gradleup.shadow') }}
      && ${{ ! contains(github.event.pull_request.title, 'me.modmuss50.mod-publish-plugin') }}
      && ${{ ! contains(github.event.pull_request.title, 'dev.architectury.loom') }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Update Readme
        run: ./gradlew processReadMeTemplate
      - name: Update Changelog
        env:
          PR_NAME: ${{ github.event.pull_request.title }}
        run: echo '- '$PR_NAME >> changelog.md
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update markdown'
