name: publish-maven

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        uses: Wandalen/wretry.action@master
        with:
          command: ./gradlew buildAllVersions --stacktrace
      - name: Publish with Gradle
        run: ./gradlew publish --stacktrace
        env:
          NYON_USERNAME: ${{ secrets.NYON_USERNAME }}
          NYON_PASSWORD: ${{ secrets.NYON_PASSWORD }}